spring.application.name=sombot-easy

spring.datasource.url=jdbc:postgresql://localhost:55433/sombot
spring.datasource.username=seanglay
spring.datasource.password=seanglay@sombot
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
